server:
  port: 8234
  servlet:
    context-path: /watchTogether
  tomcat:
    uri-encoding: utf-8
    max-connections: 10000
    connection-timeout: 20000

logging:
  level:
    root: info
    com.nfe.h5videoactionsync: debug
